services:
  - type: web
    name: axiablog
    env: php
    plan: free
    region: frankfurt # <-- Changed to Frankfurt for better performance in Nigeria

    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      npm ci --no-audit --no-fund
      npm run build
      php artisan optimize:clear
      php artisan optimize

    startCommand: "php -d variables_order=EGPCS -S 0.0.0.0:8000 public/index.php" # <-- Leave this unchanged

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
