services:
  - type: web
    name: axiablog
    env: docker
    plan: free
    region: frankfurt

    docker:
      dockerfile: Dockerfile

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://axiablog.onrender.com
